name: faultdis
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - pyproj
  - pandas
  - geopandas
  - jupyterlab
  - ipympl
  - meshio
  - tqdm
  - h5py
  - cutde
  - pip
  - pip:
      - gmsh
