
cmiDepth : 40 # cmi depth

planeDepth : 40 # clipping plane for the subduction zone, same as cmiDepth unless using a "cold nose" model

spatiallyVariable : True

smoothing : 
  fault : 1.0e+14
  cmi : 4.0e+14

cmi :
  minLon : 125
  minLat : 34

constraint : 
  faultEdge : 1.0e+4
  #faultSide : 1
  #faultUpper: 1 # upper 20 km
  cmiEdge : 1.0e+2

inputs :
  fault : "japan.msh"
  cmi : "horiz" # written by meshCmi in prepareMeshes.py
  gps : "cumulative_disp.txt"

results :
  saveFigures : False # true false figures saved to external directory
  slipDist : True # slip distribution figure
  dispSep : True  # displacements separated by component (from cmi, from fault)
  allDisp : False # figure with total displacement, predicted and observed
  crossFig : False  # cross cutting figure
  ratioFig : True # ratio of cmi displacement to total displacement
  residFig : True # displacement residuals figure
  saveData: False # numerical data
  testName : ""
